In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import os
os.chdir('/content/gdrive/')
os.getcwd()

'/content/gdrive'

In [3]:
path = '/content/gdrive/MyDrive/'
files = os.listdir(path)

In [4]:
import numpy as np
import os
import time
import pickle
import cv2
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from keras import backend as K
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model, load_model 
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D, Input
from keras import backend as k 
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping
from keras.optimizers import Adam, RMSprop, SGD
from keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from skimage.transform import resize
from sklearn.svm import SVC

In [5]:
labels = []
feature_list = []
feature_dict=pickle.load(open('/content/gdrive/MyDrive/features_till_flatten_validation.pkl','rb'))
names = [0,1]
for cat,features  in feature_dict.items():
    labels.extend([int(cat)] * len(features))
    feature_list.append(features)
feature_list = np.concatenate(feature_list)

In [6]:
feature_dict

{0: [array([[0.17568368, 0.        , 0.        , ..., 0.        , 0.66582674,
          0.        ]], dtype=float32),
  array([[0.        , 0.        , 0.        , ..., 0.34008044, 0.16917112,
          0.        ]], dtype=float32),
  array([[0.16363007, 0.        , 0.        , ..., 0.        , 0.6889629 ,
          0.        ]], dtype=float32),
  array([[0.        , 0.        , 0.        , ..., 0.        , 0.90043247,
          0.        ]], dtype=float32),
  array([[0.18818735, 0.        , 0.        , ..., 0.05211809, 0.7750498 ,
          0.        ]], dtype=float32),
  array([[0.        , 0.        , 0.        , ..., 0.09753598, 0.31750828,
          0.        ]], dtype=float32),
  array([[0.        , 0.        , 0.        , ..., 0.29505223, 0.6111631 ,
          0.        ]], dtype=float32),
  array([[0.02852505, 0.        , 0.        , ..., 0.10802534, 0.7787566 ,
          0.        ]], dtype=float32),
  array([[0.        , 0.        , 0.        , ..., 0.        , 0.44470567,
  

In [7]:
feature_list1=[]
for i in range(0,len(feature_list)):
    feature_list1.append(feature_list[i].ravel())

In [8]:
clf = SVC(kernel='rbf', probability=True).fit(feature_list1,labels )

In [9]:
count=0
for i in feature_list:
    print("Prediction : "+str(clf.predict(i)[0]),end='')
    print("   Actual is : "+str(labels[count]))
    count=count+1

Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 1   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Predicti